### ISSUE TITLE
Sending a message to group chat

### ISSUE THREAD

**Issue by UmangThapliyal** [davidchua/pymessenger#59]
Right now pymessenger supports sending message to one user only. There should be feature by which we can message a group chat

**Comment by Cretezy** [comment]
This isn't possible by the Facebook Messenger platform. A bot can only reply to a one-on-one conversation directly to a single user.

**Comment by UmangThapliyal** [comment]
@Cretezy  we did a slight modification in code and now its working

**Comment by Cretezy** [comment]
Wow, this must be new. Can you link me to supporting documentation, I've never heard of this!
Make a PR if you want too

**Comment by UmangThapliyal** [comment]
@Cretezy I will send a pull request, please check the code and approve it if you feel its okay.

**Comment by UmangThapliyal** [comment]
@Cretezy  I forked and created a pull request can you please check and approve it

**Comment by gabriellydeandrade** [comment]
Hi there, I am having the same problem. I am using pymessager version 0.0.7.0, the last one available in pypi, and since the PR was not merged there isn't this part that @UmangThapliyal changed in code. 

I see that exists other versions of pymessager such as pymessager2 and pymessager3. Does anybody recommend something?

Tks
